name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    if: github.repository == 'oakoss/account-switch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate bot token
        id: bot-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ steps.bot-token.outputs.token }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Configure npm registry for OIDC
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          registry-url: https://registry.npmjs.org

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@e87c8ed249971350e47fab7515075f44eb134e5b # v1
        with:
          publish: pnpm changeset:release
          version: pnpm changeset:version
          commit: 'chore(release): version package'
          title: 'chore(release): version package'
          commitMode: github-api
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ steps.bot-token.outputs.token }}
